/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 38
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 23
#define ALIAS_COUNT 0
#define TOKEN_COUNT 12
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LT = 1,
  anon_sym_SLASH_GT = 2,
  anon_sym_LT_SLASH = 3,
  anon_sym_GT = 4,
  aux_sym_tag_name_token1 = 5,
  anon_sym_EQ = 6,
  aux_sym_attribute_token1 = 7,
  anon_sym_LBRACE = 8,
  aux_sym_expression_token1 = 9,
  anon_sym_RBRACE = 10,
  sym_markdown = 11,
  sym_document = 12,
  sym_jsx_component = 13,
  sym_jsx_opening_tag = 14,
  sym_jsx_closing_tag = 15,
  sym_tag_name = 16,
  sym_attribute = 17,
  sym_jsx_content = 18,
  sym_expression = 19,
  aux_sym_document_repeat1 = 20,
  aux_sym_jsx_component_repeat1 = 21,
  aux_sym_jsx_opening_tag_repeat1 = 22,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT] = "<",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_GT] = ">",
  [aux_sym_tag_name_token1] = "tag_name_token1",
  [anon_sym_EQ] = "=",
  [aux_sym_attribute_token1] = "attribute_token1",
  [anon_sym_LBRACE] = "{",
  [aux_sym_expression_token1] = "expression_token1",
  [anon_sym_RBRACE] = "}",
  [sym_markdown] = "markdown",
  [sym_document] = "document",
  [sym_jsx_component] = "jsx_component",
  [sym_jsx_opening_tag] = "jsx_opening_tag",
  [sym_jsx_closing_tag] = "jsx_closing_tag",
  [sym_tag_name] = "tag_name",
  [sym_attribute] = "attribute",
  [sym_jsx_content] = "jsx_content",
  [sym_expression] = "expression",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_jsx_component_repeat1] = "jsx_component_repeat1",
  [aux_sym_jsx_opening_tag_repeat1] = "jsx_opening_tag_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_GT] = anon_sym_GT,
  [aux_sym_tag_name_token1] = aux_sym_tag_name_token1,
  [anon_sym_EQ] = anon_sym_EQ,
  [aux_sym_attribute_token1] = aux_sym_attribute_token1,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [aux_sym_expression_token1] = aux_sym_expression_token1,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_markdown] = sym_markdown,
  [sym_document] = sym_document,
  [sym_jsx_component] = sym_jsx_component,
  [sym_jsx_opening_tag] = sym_jsx_opening_tag,
  [sym_jsx_closing_tag] = sym_jsx_closing_tag,
  [sym_tag_name] = sym_tag_name,
  [sym_attribute] = sym_attribute,
  [sym_jsx_content] = sym_jsx_content,
  [sym_expression] = sym_expression,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_jsx_component_repeat1] = aux_sym_jsx_component_repeat1,
  [aux_sym_jsx_opening_tag_repeat1] = aux_sym_jsx_opening_tag_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_tag_name_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_attribute_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_expression_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_markdown] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_jsx_component] = {
    .visible = true,
    .named = true,
  },
  [sym_jsx_opening_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_jsx_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_jsx_content] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_jsx_component_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_jsx_opening_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 3,
  [5] = 2,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 17,
  [21] = 16,
  [22] = 19,
  [23] = 18,
  [24] = 14,
  [25] = 25,
  [26] = 26,
  [27] = 26,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 12,
  [34] = 34,
  [35] = 30,
  [36] = 32,
  [37] = 34,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '<') ADVANCE(9);
      if (lookahead == '=') ADVANCE(16);
      if (lookahead == '>') ADVANCE(13);
      if (lookahead == '{') ADVANCE(18);
      if (lookahead == '}') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(17);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(24);
      if (lookahead == '<') ADVANCE(9);
      if (lookahead == '{') ADVANCE(18);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(22);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(24);
      if (lookahead == '<') ADVANCE(9);
      if (lookahead == '{') ADVANCE(18);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 4:
      if (lookahead == '>') ADVANCE(10);
      END_STATE();
    case 5:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(20);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      if (lookahead == '<') ADVANCE(8);
      if (lookahead == '{') ADVANCE(18);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(12);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '{') ADVANCE(26);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_tag_name_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_tag_name_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '<' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(26);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_attribute_token1);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_expression_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(20);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_expression_token1);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_markdown);
      if (lookahead == '/') ADVANCE(24);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '{') ADVANCE(26);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_markdown);
      if (lookahead == '/') ADVANCE(24);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '<' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(26);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_markdown);
      if (lookahead == '>') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '{') ADVANCE(26);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_markdown);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '{') ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_markdown);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '{') ADVANCE(26);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 6},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 6},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 6},
  [21] = {.lex_state = 6},
  [22] = {.lex_state = 6},
  [23] = {.lex_state = 6},
  [24] = {.lex_state = 6},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 5},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 5},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [aux_sym_tag_name_token1] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [aux_sym_attribute_token1] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(29),
    [sym_jsx_component] = STATE(8),
    [sym_jsx_opening_tag] = STATE(2),
    [sym_expression] = STATE(8),
    [aux_sym_document_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LT] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [sym_markdown] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      anon_sym_SLASH_GT,
    ACTIONS(13), 1,
      anon_sym_LT_SLASH,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      sym_markdown,
    STATE(5), 1,
      sym_jsx_opening_tag,
    STATE(24), 1,
      sym_jsx_closing_tag,
    STATE(4), 2,
      sym_jsx_content,
      aux_sym_jsx_component_repeat1,
    STATE(15), 2,
      sym_jsx_component,
      sym_expression,
  [30] = 9,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      sym_markdown,
    ACTIONS(19), 1,
      anon_sym_SLASH_GT,
    ACTIONS(21), 1,
      anon_sym_LT_SLASH,
    STATE(5), 1,
      sym_jsx_opening_tag,
    STATE(19), 1,
      sym_jsx_closing_tag,
    STATE(6), 2,
      sym_jsx_content,
      aux_sym_jsx_component_repeat1,
    STATE(15), 2,
      sym_jsx_component,
      sym_expression,
  [60] = 9,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      anon_sym_SLASH_GT,
    ACTIONS(13), 1,
      anon_sym_LT_SLASH,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      sym_markdown,
    STATE(5), 1,
      sym_jsx_opening_tag,
    STATE(22), 1,
      sym_jsx_closing_tag,
    STATE(6), 2,
      sym_jsx_content,
      aux_sym_jsx_component_repeat1,
    STATE(15), 2,
      sym_jsx_component,
      sym_expression,
  [90] = 9,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      sym_markdown,
    ACTIONS(19), 1,
      anon_sym_SLASH_GT,
    ACTIONS(21), 1,
      anon_sym_LT_SLASH,
    STATE(5), 1,
      sym_jsx_opening_tag,
    STATE(14), 1,
      sym_jsx_closing_tag,
    STATE(3), 2,
      sym_jsx_content,
      aux_sym_jsx_component_repeat1,
    STATE(15), 2,
      sym_jsx_component,
      sym_expression,
  [120] = 7,
    ACTIONS(23), 1,
      anon_sym_LT,
    ACTIONS(28), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym_markdown,
    STATE(5), 1,
      sym_jsx_opening_tag,
    ACTIONS(26), 2,
      anon_sym_SLASH_GT,
      anon_sym_LT_SLASH,
    STATE(6), 2,
      sym_jsx_content,
      aux_sym_jsx_component_repeat1,
    STATE(15), 2,
      sym_jsx_component,
      sym_expression,
  [145] = 3,
    ACTIONS(36), 1,
      aux_sym_tag_name_token1,
    STATE(9), 2,
      sym_attribute,
      aux_sym_jsx_opening_tag_repeat1,
    ACTIONS(34), 5,
      anon_sym_LT,
      anon_sym_SLASH_GT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_markdown,
  [160] = 6,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(38), 1,
      ts_builtin_sym_end,
    ACTIONS(40), 1,
      sym_markdown,
    STATE(2), 1,
      sym_jsx_opening_tag,
    STATE(11), 3,
      sym_jsx_component,
      sym_expression,
      aux_sym_document_repeat1,
  [181] = 3,
    ACTIONS(44), 1,
      aux_sym_tag_name_token1,
    STATE(9), 2,
      sym_attribute,
      aux_sym_jsx_opening_tag_repeat1,
    ACTIONS(42), 5,
      anon_sym_LT,
      anon_sym_SLASH_GT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_markdown,
  [196] = 3,
    ACTIONS(36), 1,
      aux_sym_tag_name_token1,
    STATE(7), 2,
      sym_attribute,
      aux_sym_jsx_opening_tag_repeat1,
    ACTIONS(47), 5,
      anon_sym_LT,
      anon_sym_SLASH_GT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_markdown,
  [211] = 6,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    ACTIONS(51), 1,
      anon_sym_LT,
    ACTIONS(54), 1,
      anon_sym_LBRACE,
    ACTIONS(57), 1,
      sym_markdown,
    STATE(2), 1,
      sym_jsx_opening_tag,
    STATE(11), 3,
      sym_jsx_component,
      sym_expression,
      aux_sym_document_repeat1,
  [232] = 1,
    ACTIONS(60), 6,
      anon_sym_LT,
      anon_sym_SLASH_GT,
      anon_sym_LT_SLASH,
      aux_sym_tag_name_token1,
      anon_sym_LBRACE,
      sym_markdown,
  [241] = 1,
    ACTIONS(62), 6,
      anon_sym_LT,
      anon_sym_SLASH_GT,
      anon_sym_LT_SLASH,
      aux_sym_tag_name_token1,
      anon_sym_LBRACE,
      sym_markdown,
  [250] = 1,
    ACTIONS(64), 5,
      anon_sym_LT,
      anon_sym_SLASH_GT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_markdown,
  [258] = 1,
    ACTIONS(66), 5,
      anon_sym_LT,
      anon_sym_SLASH_GT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_markdown,
  [266] = 1,
    ACTIONS(68), 5,
      anon_sym_LT,
      anon_sym_SLASH_GT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_markdown,
  [274] = 1,
    ACTIONS(70), 5,
      anon_sym_LT,
      anon_sym_SLASH_GT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_markdown,
  [282] = 1,
    ACTIONS(72), 5,
      anon_sym_LT,
      anon_sym_SLASH_GT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_markdown,
  [290] = 1,
    ACTIONS(74), 5,
      anon_sym_LT,
      anon_sym_SLASH_GT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_markdown,
  [298] = 2,
    ACTIONS(70), 2,
      anon_sym_LT,
      anon_sym_LBRACE,
    ACTIONS(76), 2,
      ts_builtin_sym_end,
      sym_markdown,
  [307] = 2,
    ACTIONS(68), 2,
      anon_sym_LT,
      anon_sym_LBRACE,
    ACTIONS(78), 2,
      ts_builtin_sym_end,
      sym_markdown,
  [316] = 2,
    ACTIONS(74), 2,
      anon_sym_LT,
      anon_sym_LBRACE,
    ACTIONS(80), 2,
      ts_builtin_sym_end,
      sym_markdown,
  [325] = 2,
    ACTIONS(72), 2,
      anon_sym_LT,
      anon_sym_LBRACE,
    ACTIONS(82), 2,
      ts_builtin_sym_end,
      sym_markdown,
  [334] = 2,
    ACTIONS(64), 2,
      anon_sym_LT,
      anon_sym_LBRACE,
    ACTIONS(84), 2,
      ts_builtin_sym_end,
      sym_markdown,
  [343] = 2,
    ACTIONS(86), 1,
      aux_sym_tag_name_token1,
    STATE(10), 1,
      sym_tag_name,
  [350] = 2,
    ACTIONS(88), 1,
      aux_sym_tag_name_token1,
    STATE(32), 1,
      sym_tag_name,
  [357] = 2,
    ACTIONS(88), 1,
      aux_sym_tag_name_token1,
    STATE(36), 1,
      sym_tag_name,
  [364] = 1,
    ACTIONS(90), 1,
      anon_sym_EQ,
  [368] = 1,
    ACTIONS(92), 1,
      ts_builtin_sym_end,
  [372] = 1,
    ACTIONS(94), 1,
      anon_sym_RBRACE,
  [376] = 1,
    ACTIONS(96), 1,
      aux_sym_attribute_token1,
  [380] = 1,
    ACTIONS(98), 1,
      anon_sym_GT,
  [384] = 1,
    ACTIONS(100), 1,
      anon_sym_GT,
  [388] = 1,
    ACTIONS(102), 1,
      aux_sym_expression_token1,
  [392] = 1,
    ACTIONS(104), 1,
      anon_sym_RBRACE,
  [396] = 1,
    ACTIONS(106), 1,
      anon_sym_GT,
  [400] = 1,
    ACTIONS(108), 1,
      aux_sym_expression_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 30,
  [SMALL_STATE(4)] = 60,
  [SMALL_STATE(5)] = 90,
  [SMALL_STATE(6)] = 120,
  [SMALL_STATE(7)] = 145,
  [SMALL_STATE(8)] = 160,
  [SMALL_STATE(9)] = 181,
  [SMALL_STATE(10)] = 196,
  [SMALL_STATE(11)] = 211,
  [SMALL_STATE(12)] = 232,
  [SMALL_STATE(13)] = 241,
  [SMALL_STATE(14)] = 250,
  [SMALL_STATE(15)] = 258,
  [SMALL_STATE(16)] = 266,
  [SMALL_STATE(17)] = 274,
  [SMALL_STATE(18)] = 282,
  [SMALL_STATE(19)] = 290,
  [SMALL_STATE(20)] = 298,
  [SMALL_STATE(21)] = 307,
  [SMALL_STATE(22)] = 316,
  [SMALL_STATE(23)] = 325,
  [SMALL_STATE(24)] = 334,
  [SMALL_STATE(25)] = 343,
  [SMALL_STATE(26)] = 350,
  [SMALL_STATE(27)] = 357,
  [SMALL_STATE(28)] = 364,
  [SMALL_STATE(29)] = 368,
  [SMALL_STATE(30)] = 372,
  [SMALL_STATE(31)] = 376,
  [SMALL_STATE(32)] = 380,
  [SMALL_STATE(33)] = 384,
  [SMALL_STATE(34)] = 388,
  [SMALL_STATE(35)] = 392,
  [SMALL_STATE(36)] = 396,
  [SMALL_STATE(37)] = 400,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_jsx_component_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [26] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_jsx_component_repeat1, 2, 0, 0),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_jsx_component_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_jsx_component_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [34] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jsx_opening_tag, 3, 0, 1),
  [36] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [42] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_jsx_opening_tag_repeat1, 2, 0, 0),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_jsx_opening_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jsx_opening_tag, 2, 0, 1),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_name, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 3, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jsx_component, 2, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jsx_content, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jsx_closing_tag, 1, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jsx_closing_tag, 3, 0, 1),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jsx_component, 3, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jsx_closing_tag, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jsx_component, 3, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jsx_closing_tag, 3, 0, 1),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jsx_component, 2, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [92] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_name, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_mdx(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "mdx",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
